# Generated by Django 4.1.4 on 2023-05-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PredCarbonData', models.FloatField()),
                ('PredictDate', models.DateField()),
                ('PredCarbonTrans', models.FloatField()),
                ('Com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
