# Generated by Django 4.1.4 on 2023-05-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carbon', '__first__'),
        ('Company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PredCarbonData', models.FloatField()),
                ('PredictDate', models.DateField()),
                ('PredCarbonTrans', models.FloatField()),
                ('Cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='Carbon.category')),
                ('Com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
