# Generated by Django 4.1.4 on 2023-01-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CarbonActivity", models.TextField()),
                ("CarbonData", models.FloatField()),
                ("CarbonUnit", models.TextField()),
                ("CarbonTrans", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CarbonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("Location", models.TextField()),
                ("Scope", models.IntegerField()),
                ("Category", models.IntegerField()),
                ("Division", models.TextField()),
            ],
        ),
    ]
