# Generated by Django 4.1.4 on 2023-05-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DecreTotalEmission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DecreMethid', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseEmissions', models.IntegerField()),
                ('Com_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalDate', models.DateField()),
                ('Goal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='CarbonNature.goal')),
            ],
        ),
    ]
