# Generated by Django 4.1.4 on 2023-05-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonNature', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='TransEnergy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TListReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listkind', models.IntegerField()),
                ('index', models.IntegerField()),
                ('category', models.TextField()),
                ('percentage', models.IntegerField()),
                ('target', models.TextField(blank=True, null=True)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TListGoal', to='CarbonNature.goal')),
            ],
        ),
    ]
